name: build-image
on:
  push:
    branches:
      - 'main'
    paths:
      - '.coder/img/**' # only run the action when .coder/img has been modified
  workflow_dispatch:
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.1
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get short SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          # Change projectname in both places:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-project:latest, ${{ secrets.DOCKERHUB_USERNAME }}/your-project:${{ steps.vars.outputs.sha_short }}
          context: .coder/img/
          file: .coder/img/Dockerfile
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
